---
- name: Provision Google Cloud Infrastructure
  hosts: localhost
  connection: local
  vars:
    project_id: "indigo-muse-471516-b8"
    region: "us-central1"
    zone: "us-central1-a"
    cluster_name: "lpg-gke-cluster"
    repo_name: "lpg-docker-repo"

  tasks:
    - name: 1. Enable required GCP APIs
      command: gcloud services enable container.googleapis.com artifactregistry.googleapis.com --project={{ project_id }}

    - name: 2. Create Artifact Registry
      command: >
        gcloud artifacts repositories create {{ repo_name }}
        --repository-format=docker
        --location={{ region }}
        --description="Docker repository for Smart LPG App"
        --project={{ project_id }}
      register: repo_result
      failed_when: 
        - repo_result.rc != 0
        - "'already exists' not in repo_result.stderr"
      changed_when: "'already exists' not in repo_result.stderr"

    - name: 3. Create GKE Cluster
      command: >
        gcloud container clusters create {{ cluster_name }}
        --zone={{ zone }}
        --num-nodes=1
        --machine-type=e2-small
        --disk-size=20GB
        --project={{ project_id }}
      register: cluster_result
      failed_when: 
        - cluster_result.rc != 0
        - "'already exists' not in cluster_result.stderr"
      changed_when: "'already exists' not in cluster_result.stderr"

    - name: 4. Get Kubernetes Credentials
      command: gcloud container clusters get-credentials {{ cluster_name }} --zone={{ zone }} --project={{ project_id }}